language: java

install: true

jdk:
  - oraclejdk8

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

services:
  - docker

before_script:
  - sudo apt-get install expect
  - docker pull sath89/oracle-12c

script:
  - docker run -d --name db1 -p 8080:8080 -p 1522:1521 sath89/oracle-12c
  - docker run -d --name db2 -p 8081:8080 -p 1523:1521 sath89/oracle-12c

  - chmod +x find_in_docker_logs.sh

  - sh find_in_docker_logs.sh db1 500 "Database ready to use"
  - sh find_in_docker_logs.sh db2 500 "Database ready to use"

  - ./gradlew
