version: '2'

#volumes:
#    prometheus_data: {}

services:
  prometheus:
    image: prom/prometheus:v1.7.2
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '-config.file=/etc/prometheus/prometheus.yml'
      - '-storage.local.path=/prometheus'
    expose:
      - 9090
    links:
      - patterdale

  patterdale:
    image: tjheslin1/patterdale:DEV-SNAPSHOT
    volumes:
      - ./repo/ojdbc7.jar:/app/ojdbc7.jar
      - ./src/test/resources:/config
      - ./src/test/resources:/passwords
    command:
      - 'java'
      - '-jar'
      - '-Dlogback.configurationFile=/config/logback.xml'
      - '-Dconfig.file=/config/patterdale.yml'
      - '-Dpasswords.file=/passwords/passwords.yml'
      - 'patterdale-all.jar'
      - '-Dconfig.file=/config/patterdale.yml'
      - '-Dpasswords.file=/passwords/passwords.yml'
      - '-Dlogback.configurationFile=/config/logback.xml'
    expose:
      - 7001

#    oracle:
#      image
